version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: product-discounter:latest
    restart: on-failure
    ports:
      - '8080:80'
    depends_on:
      - db
    hostname: product-discounter
    command: bash -c "vendor/bin/mongo-migrator migrate && apachectl -D FOREGROUND"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      - API_BASE_URL=web:80/
      - MONGODB_HOST=db
  db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
  swagger:
    image: swaggerapi/swagger-ui
    restart: on-failure
    ports:
      - '8081:8080'
    depends_on:
      - web
    environment:
      - API_URL= http://localhost:8080/doc/api-doc.yaml
volumes:
  vendor:
